###Pegar todos os Produtos
get http://localhost:3000/produto/all

###Adicionar um produto
post http://localhost:3000/produto/create
Content-Type: application/json

{
    "nome": "Halo",
    "preco": 150,
    "img": "https://bdjogos.com.br/capas/10529-halo-combat-evolved-anniversary-xbox-360-capa-1.jpg"
}

###Pegar um Produto
get http://localhost:3000/produto/get/2efc02a5-de82-45a4-bc32-20d6ad844e59

###Atualizar um produto
patch http://localhost:3000/produto/update/bbe90f82-4a54-4b07-a628-9ba751c3ea29
Content-Type: application/json

{
    "nome":"God of War Ragnarok",
    "preco":15.90
}

###Deletar um produto
delete http://localhost:3000/produto/delete/2efc02a5-de82-45a4-bc32-20d6ad844e59