###Pegar todos os Produtos
get http://localhost:3000/produto/all

###Adicionar um produto
post http://localhost:3000/produto/create
Content-Type: application/json

{
    "nome": "da3s",
    "preco": 2153,
    "img": "https://img.freepik.com/fotos-gratis/o-gato-vermelho-ou-branco-eu-no-estudio-branco_155003-13189.jpg"
}

###Pegar um Produto
get http://localhost:3000/produto/get/3a3a6500-5826-4bea-a445-3ce6b45c2a34

###Atualizar um produto
patch http://localhost:3000/produto/update/b4711003-1cbe-4976-83c5-09d01aa2246d
Content-Type: application/json

{
    "nome":"God of War Ragnarok",
    "preco":15.90
}

###Deletar um produto
delete http://localhost:3000/produto/delete/3a3a6500-5826-4bea-a445-3ce6b45c2a34